### ISSUE TITLE
powrap exits status 1 when done what is expected

### ISSUE THREAD

**Issue by rffontenelle** [JulienPalard/powrap#19]
_powrap_ returns exit status 1 when at least one file was modified.  When running in a Makefile this can problematic because it may end with error status and without any clue. It is possible to work around it with `powrap *.po **/*.po || true`, but then real problems will not be spotted.

NOTE: This is documented in `--help` for the `--check` flag, but not documented for normal run (e.g. `powrap *.po **/*.po`).

Please consider adding a flag that disable this (or disable by default and add flag that enable this).

**Comment by JulienPalard** [comment]
Now that we have `--check` it was nonsensical to return `-1` when the program did something. I dropped this "feature".
